language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test -- --coverage

deploy:
  provider: pages
  local-dir: ./build
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master